export const orderFormData = {
  items: [
    {
      uniqueId: '6D0BDD7B3A454940A449922D157A6FC0',
      id: '8',
      productId: '4',
      productRefId: '04-Suiza-Negro-flores',
      refId: '8',
      ean: null,
      name: 'Blusa Suiza Negro flores Talla S - Color Negro flores',
      skuName: 'Talla S - Color Negro flores',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2023-05-13T04:03:02Z',
      tax: 0,
      price: 58000,
      listPrice: 58000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 58000,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Amalia',
        brandId: '2000000',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/2/',
      productCategories: { '1': 'Moda', '2': 'Blusas' },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://amalia.vteximg.com.br/arquivos/ids/158065-300-360/04-suiza-flores_negra-1.jpg?v=637460854554700000',
      detailUrl: '/blusa-suiza-negro-flores/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 5800000,
        total: 5800000,
        sellingPrices: [{ value: 5800000, quantity: 1 }],
      },
    },
    {
      uniqueId: '2AA04EFE998142C186A570532C87B84F',
      id: '4',
      productId: '2',
      productRefId: '02-Suecia-Rayas-colores',
      refId: '4',
      ean: null,
      name: 'Chaleco Suecia Rayas colores Talla XS/S - Color Rayas colores',
      skuName: 'Talla XS/S - Color Rayas colores',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2023-05-13T04:03:02Z',
      tax: 0,
      price: 69000,
      listPrice: 89000,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 34500,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'Amalia',
        brandId: '2000000',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/5/',
      productCategories: { '1': 'Moda', '5': 'Chalecos' },
      quantity: 1,
      seller: '1',
      sellerChain: ['1'],
      imageUrl:
        'http://amalia.vteximg.com.br/arquivos/ids/158061-300-360/02-Suecia-Rayas-colores-1.jpg?v=637460854523970000',
      detailUrl: '/chaleco-suecia-rayas-colores/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [],
      priceTags: [],
      availability: 'available',
      measurementUnit: 'kg',
      unitMultiplier: 0.5,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 3450000,
        total: 3450000,
        sellingPrices: [{ value: 3450000, quantity: 1 }],
      },
    },
  ],
  totalizers: [
    { id: 'Items', name: 'Total de los items', value: 9250000 },
    { id: 'Shipping', name: 'Costo total del envío', value: 500000 },
  ],
  value: 97500,
  paymentData: {
    availablePaymentMethods: [
      {
        franchise: 'Visa',
        id: '7339A0C8664F49148335AB60915016AC',
        number: '1111',
        paymentMethod: 'tc',
        bin: '411111',
        origin: 'store',
      },
    ],
    installmentOptions: [
      {
        paymentSystem: '1',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 4875000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 4875000,
                total: 9750000,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 3250000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 3250000,
                total: 9750000,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 2437500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 2437500,
                total: 9750000,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 1950000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 1950000,
                total: 9750000,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 1625000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 1625000,
                total: 9750000,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 1392900,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 1392900,
                total: 9750000,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 1218800,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 1218800,
                total: 9750000,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 1083400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 1083400,
                total: 9750000,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 975000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 975000,
                total: 9750000,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 886400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 886400,
                total: 9750000,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 812500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 812500,
                total: 9750000,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 696500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 696500,
                total: 9750000,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 650000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 650000,
                total: 9750000,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 609400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 609400,
                total: 9750000,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 573600,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 573600,
                total: 9750000,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 541700,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 541700,
                total: 9750000,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 513200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 513200,
                total: 9750000,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 487500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 487500,
                total: 9750000,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 464300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 464300,
                total: 9750000,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 443200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 443200,
                total: 9750000,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 424000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 424000,
                total: 9750000,
              },
            ],
          },
          {
            count: 24,
            hasInterestRate: false,
            interestRate: 0,
            value: 406300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 24,
                hasInterestRate: false,
                interestRate: 0,
                value: 406300,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '2',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 4875000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 4875000,
                total: 9750000,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 3250000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 3250000,
                total: 9750000,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 2437500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 2437500,
                total: 9750000,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 1950000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 1950000,
                total: 9750000,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 1625000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 1625000,
                total: 9750000,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 1392900,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 1392900,
                total: 9750000,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 1218800,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 1218800,
                total: 9750000,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 1083400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 1083400,
                total: 9750000,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 975000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 975000,
                total: 9750000,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 886400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 886400,
                total: 9750000,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 812500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 812500,
                total: 9750000,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 696500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 696500,
                total: 9750000,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 650000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 650000,
                total: 9750000,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 609400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 609400,
                total: 9750000,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 573600,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 573600,
                total: 9750000,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 541700,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 541700,
                total: 9750000,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 513200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 513200,
                total: 9750000,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 487500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 487500,
                total: 9750000,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 464300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 464300,
                total: 9750000,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 443200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 443200,
                total: 9750000,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 424000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 424000,
                total: 9750000,
              },
            ],
          },
          {
            count: 24,
            hasInterestRate: false,
            interestRate: 0,
            value: 406300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 24,
                hasInterestRate: false,
                interestRate: 0,
                value: 406300,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '3',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 4875000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 4875000,
                total: 9750000,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 3250000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 3250000,
                total: 9750000,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 2437500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 2437500,
                total: 9750000,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 1950000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 1950000,
                total: 9750000,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 1625000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 1625000,
                total: 9750000,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 1392900,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 1392900,
                total: 9750000,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 1218800,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 1218800,
                total: 9750000,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 1083400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 1083400,
                total: 9750000,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 975000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 975000,
                total: 9750000,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 886400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 886400,
                total: 9750000,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 812500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 812500,
                total: 9750000,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 696500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 696500,
                total: 9750000,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 650000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 650000,
                total: 9750000,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 609400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 609400,
                total: 9750000,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 573600,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 573600,
                total: 9750000,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 541700,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 541700,
                total: 9750000,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 513200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 513200,
                total: 9750000,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 487500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 487500,
                total: 9750000,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 464300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 464300,
                total: 9750000,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 443200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 443200,
                total: 9750000,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 424000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 424000,
                total: 9750000,
              },
            ],
          },
          {
            count: 24,
            hasInterestRate: false,
            interestRate: 0,
            value: 406300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 24,
                hasInterestRate: false,
                interestRate: 0,
                value: 406300,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 4875000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 4875000,
                total: 9750000,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 3250000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 3250000,
                total: 9750000,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 2437500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 2437500,
                total: 9750000,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 1950000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 1950000,
                total: 9750000,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 1625000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 1625000,
                total: 9750000,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 1392900,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 1392900,
                total: 9750000,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 1218800,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 1218800,
                total: 9750000,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 1083400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 1083400,
                total: 9750000,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 975000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 975000,
                total: 9750000,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 886400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 886400,
                total: 9750000,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 812500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 812500,
                total: 9750000,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 696500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 696500,
                total: 9750000,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 650000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 650000,
                total: 9750000,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 609400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 609400,
                total: 9750000,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 573600,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 573600,
                total: 9750000,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 541700,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 541700,
                total: 9750000,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 513200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 513200,
                total: 9750000,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 487500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 487500,
                total: 9750000,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 464300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 464300,
                total: 9750000,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 443200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 443200,
                total: 9750000,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 424000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 424000,
                total: 9750000,
              },
            ],
          },
          {
            count: 24,
            hasInterestRate: false,
            interestRate: 0,
            value: 406300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 24,
                hasInterestRate: false,
                interestRate: 0,
                value: 406300,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '201',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '206',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '2',
        bin: '411111',
        paymentName: null,
        paymentGroupName: null,
        value: 9750000,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 9750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 9750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 4875000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 4875000,
                total: 9750000,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 3250000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 3250000,
                total: 9750000,
              },
            ],
          },
          {
            count: 4,
            hasInterestRate: false,
            interestRate: 0,
            value: 2437500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 4,
                hasInterestRate: false,
                interestRate: 0,
                value: 2437500,
                total: 9750000,
              },
            ],
          },
          {
            count: 5,
            hasInterestRate: false,
            interestRate: 0,
            value: 1950000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 5,
                hasInterestRate: false,
                interestRate: 0,
                value: 1950000,
                total: 9750000,
              },
            ],
          },
          {
            count: 6,
            hasInterestRate: false,
            interestRate: 0,
            value: 1625000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 6,
                hasInterestRate: false,
                interestRate: 0,
                value: 1625000,
                total: 9750000,
              },
            ],
          },
          {
            count: 7,
            hasInterestRate: false,
            interestRate: 0,
            value: 1392900,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 7,
                hasInterestRate: false,
                interestRate: 0,
                value: 1392900,
                total: 9750000,
              },
            ],
          },
          {
            count: 8,
            hasInterestRate: false,
            interestRate: 0,
            value: 1218800,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 8,
                hasInterestRate: false,
                interestRate: 0,
                value: 1218800,
                total: 9750000,
              },
            ],
          },
          {
            count: 9,
            hasInterestRate: false,
            interestRate: 0,
            value: 1083400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 9,
                hasInterestRate: false,
                interestRate: 0,
                value: 1083400,
                total: 9750000,
              },
            ],
          },
          {
            count: 10,
            hasInterestRate: false,
            interestRate: 0,
            value: 975000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 10,
                hasInterestRate: false,
                interestRate: 0,
                value: 975000,
                total: 9750000,
              },
            ],
          },
          {
            count: 11,
            hasInterestRate: false,
            interestRate: 0,
            value: 886400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 11,
                hasInterestRate: false,
                interestRate: 0,
                value: 886400,
                total: 9750000,
              },
            ],
          },
          {
            count: 12,
            hasInterestRate: false,
            interestRate: 0,
            value: 812500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 12,
                hasInterestRate: false,
                interestRate: 0,
                value: 812500,
                total: 9750000,
              },
            ],
          },
          {
            count: 13,
            hasInterestRate: false,
            interestRate: 0,
            value: 750000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 13,
                hasInterestRate: false,
                interestRate: 0,
                value: 750000,
                total: 9750000,
              },
            ],
          },
          {
            count: 14,
            hasInterestRate: false,
            interestRate: 0,
            value: 696500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 14,
                hasInterestRate: false,
                interestRate: 0,
                value: 696500,
                total: 9750000,
              },
            ],
          },
          {
            count: 15,
            hasInterestRate: false,
            interestRate: 0,
            value: 650000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 15,
                hasInterestRate: false,
                interestRate: 0,
                value: 650000,
                total: 9750000,
              },
            ],
          },
          {
            count: 16,
            hasInterestRate: false,
            interestRate: 0,
            value: 609400,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 16,
                hasInterestRate: false,
                interestRate: 0,
                value: 609400,
                total: 9750000,
              },
            ],
          },
          {
            count: 17,
            hasInterestRate: false,
            interestRate: 0,
            value: 573600,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 17,
                hasInterestRate: false,
                interestRate: 0,
                value: 573600,
                total: 9750000,
              },
            ],
          },
          {
            count: 18,
            hasInterestRate: false,
            interestRate: 0,
            value: 541700,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 18,
                hasInterestRate: false,
                interestRate: 0,
                value: 541700,
                total: 9750000,
              },
            ],
          },
          {
            count: 19,
            hasInterestRate: false,
            interestRate: 0,
            value: 513200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 19,
                hasInterestRate: false,
                interestRate: 0,
                value: 513200,
                total: 9750000,
              },
            ],
          },
          {
            count: 20,
            hasInterestRate: false,
            interestRate: 0,
            value: 487500,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 20,
                hasInterestRate: false,
                interestRate: 0,
                value: 487500,
                total: 9750000,
              },
            ],
          },
          {
            count: 21,
            hasInterestRate: false,
            interestRate: 0,
            value: 464300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 21,
                hasInterestRate: false,
                interestRate: 0,
                value: 464300,
                total: 9750000,
              },
            ],
          },
          {
            count: 22,
            hasInterestRate: false,
            interestRate: 0,
            value: 443200,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 22,
                hasInterestRate: false,
                interestRate: 0,
                value: 443200,
                total: 9750000,
              },
            ],
          },
          {
            count: 23,
            hasInterestRate: false,
            interestRate: 0,
            value: 424000,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 23,
                hasInterestRate: false,
                interestRate: 0,
                value: 424000,
                total: 9750000,
              },
            ],
          },
          {
            count: 24,
            hasInterestRate: false,
            interestRate: 0,
            value: 406300,
            total: 9750000,
            sellerMerchantInstallments: [
              {
                id: 'AMALIA',
                count: 24,
                hasInterestRate: false,
                interestRate: 0,
                value: 406300,
                total: 9750000,
              },
            ],
          },
        ],
      },
    ],
  },
  messages: [],
  marketingData: { coupon: null },
}
